apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant
  template:
    metadata:
      labels:
        app: restaurant
    spec:
      containers:
      - name: restaurant-app
        image: restaurant-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3005
        env:
        - name: PORT
          value: "3005"