apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  namespace: default
spec:
  selector:
    app: restaurant
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3005
